### ISSUE TITLE
Analyse DND dataset

### ISSUE THREAD

**Issue by patheard** [csps-efpc-daan-students-etudiants/team-6#1]
- Look for insights about cohorts.  Were there groups that benefited more than others?
- Look for data gaps that allow us to get a complete picture on the training's impact on data literacy.

**Comment by almacd13** [comment]
I have the data files in CSV on my desktop, but can't attach to this post. 


[Training.xlsx](https://github.com/csps-efpc-daan-students-etudiants/team-6/files/3228069/Training.xlsx)
[Copy of Report Usage (corrected).xlsx](https://github.com/csps-efpc-daan-students-etudiants/team-6/files/3228070/Copy.of.Report.Usage.corrected.xlsx)
[System Account Creation.xlsx](https://github.com/csps-efpc-daan-students-etudiants/team-6/files/3228071/System.Account.Creation.xlsx)

**Comment by almacd13** [comment]
- [x] import data
- [ ] join data sets
- [ ]

**Comment by almacd13** [comment]
Findings: 

In the training data: 
46 do not have a location
358 do not have a UserId
37 do not have a provider
34 have a first day of course in the year 9999
46 do not have a rank

In the User data
Number of times a report was created or reviewed --> 11189
Number of times a report was refreshed or viewed --> 139767

When Users and Training Data are joined: 
There are 671 users who do not have a first day of course.

**Comment by patheard** [comment]
The year `9999` you say?  We should ask them how things work out for us in the later half of the 21st century.

**Comment by almacd13** [comment]
User data doesn't have L1 or Rank --> can't make any statements about which groups use the software more
Reporting data doesn't have Rank --> can't make statements about which Level 1s use the software more

This would allow DND to target the appropriate people to take the trianing
