### ISSUE TITLE
Identify types of data we're looking for

### ISSUE THREAD

**Issue by patheard** [csps-efpc-daan-students-etudiants/team-6#31]
Investigate correlation vs. causation in relation to these data types.

**Comment by almacd13** [comment]
Based on the amount of time a person took to answer this question, what information is there? 
Number of tries to success? 
Time to completion vs. expectation?

**Comment by patheard** [comment]
This is now in:

- [data-types.md](https://github.com/csps-efpc-daan-students-etudiants/team-6/blob/master/research/data-types.md)
- [assessment-types.md](https://github.com/csps-efpc-daan-students-etudiants/team-6/blob/master/research/assessment-types.md)
