### ISSUE TITLE
Data analysis: feature usage

### ISSUE THREAD

**Issue by patheard** [csps-efpc-daan-students-etudiants/team-6#5]
- See if there's a way to determine if users are using basic or advanced features.
- Are they using these more before/after training?

**Comment by almacd13** [comment]
Questions for Marta
Is there more data about how people are using the software?

**Comment by almacd13** [comment]
Problems: 
Don't have access to any data about usage of the report software before/after training. Therefore, we cannot make any statements about how usage changes following training.
